apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    app: lab-operations
  name: lab-operations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-operations
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/f21ao-cw-default: "true"
        app: lab-operations
    spec:
      containers:
        - image: suhanaayishahw/lab-operations:latest
          name: lab-operations
          ports:
            - containerPort: 3002
              hostPort: 3002
              protocol: TCP
      hostname: laboperations
      restartPolicy: Always
